apiVersion: v1
kind: Service
metadata:
  name: observer-db
  namespace: observer
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: observer
    type: db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: observer-db
  namespace: observer
spec:
  serviceName: observer-db
  replicas: 1
  selector:
    matchLabels:
      app: observer
      type: db
  template:
    metadata:
      labels:
        app: observer
        type: db
        vendor: MongoDB
    spec:
      serviceAccountName: observer
      terminationGracePeriodSeconds: 10
      volumes:
        - name: observer-db
          persistentVolumeClaim:
            claimName: observer-db
      containers:
        - name: main
          image: mongo:5.0.5
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: observer
                  key: db_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: observer
                  key: db_password
          ports:
            - name: default
              containerPort: 27017
          volumeMounts:
            - name: observer-db
              mountPath: /data/db
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - db.adminCommand('ping')
            initialDelaySeconds: 10
        - name: exporter
          image: percona/mongodb_exporter:0.30.0
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: observer
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: observer
                  key: db_password
          args:
            - --web.listen-address=:9090
            - --web.telemetry-path=/metrics
            - --mongodb.uri=mongodb://$(DB_USERNAME):$(DB_PASSWORD)@localhost:27017
          ports:
            - name: metrics
              containerPort: 9090
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
  volumeClaimTemplates:
    - metadata:
        name: observer-db
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: regional-ssd
        resources:
          requests:
            storage: 1Gi

---

apiVersion: monitoring.gke.io/v1alpha1
kind: PodMonitor
metadata:
  name: observer-db
  namespace: observer
spec:
  selector:
    matchLabels:
      app: observer
      type: db
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 15s
